<?php
?>
<script>
    // Nothing here yet
</script>

<div id="anchor-content" class="anchor-content" style="padding-top:50px;padding-bottom:50px;    background-color: #ffdbb1">
<div id="container" class="main-col" style="margin: 0 auto;width: 90%;">
	<div style="text-align:center">
	<div style="color:#474ba5; font-weight:bold; font-family:calibri; font-size:25px;">Confused what to do ? 
	<a href="#" style="padding:10px;border-radius:10px;color: #e9b863;text-decoration: underline;">Read our documentation</a>
	</div>
	</div>
	<div style="clear:both"></div>
</div>

</div>

<div id="anchor-content" class="anchor-content" style="padding-top:50px;padding-bottom:50px;    background-color: #FAFAFA">
<div id="container" class="main-col" style="
    margin: 0 auto;
    width: 90%;
">
	<div style="width:50%;float:left;text-align:center"><img src="https://apps.3dcart.com/assets/images/fomo_logo_yellow.png" style="width:200px" /></div>
	<div style="width:50%;float:left">
		<div style="margin: 0 auto;width: fit-content;">
		<div style="color: #EBA06D;font-weight: 700;font-family: arial;margin-bottom:5px"><a style="color: #e4996d;font-weight: 700;font-family: arial;font-size: 20px;" href="mailto:hello@fomo.com">hello@fomo.com</a></div>

		<div style="color: #e4996d;font-weight: 700;font-family: arial;font-size: 20px;margin-bottom:5px"><span style="color: #474ba5;">call us @</span> 650.797.2709</div>

		<div style="margin-bottom:5px"><a style="color: #e4996d;font-weight: 500;font-family: arial;font-size: 18px;" href="#">we're only on Twitter, whaat?</a></div>
		</div>
	</div>
	<div style="clear:both"></div>
</div>

</div>